wip

diff --git a/.github/workflows/deploy-bucket.yml b/.github/workflows/deploy-bucket.yml
--- a/.github/workflows/deploy-bucket.yml
+++ b/.github/workflows/deploy-bucket.yml
@@ -1,7 +1,8 @@
 # This workflow deploys front end application to a object store bucket
 # Supported buckets:
 # - Aliyun OSS
-# - [to test] AWS S3
+# - AWS S3 [TOTEST]
+# - Github Pages [TOTEST]
 #
 # Setup the following github action repo secrets
 # - ACCESS_KEY_ID
@@ -9,11 +10,11 @@
 # Setup the following github action repo vars
 # - ENDPOINT
 # Specify the following during build
-# - provider (aws, oss)
+# - provider (aws, oss, ghp)
 # - tag
 # - app (the web app folder in apps folder)
 # - bucket (bucket name - e.g. test-www-dev)
-# - env (dev, uat, prd)
+# - env (development, statging, production)
 #
 name: IN USE - Deploy To Bucket
 
@@ -68,16 +69,14 @@ jobs:
         uses: actions/checkout@v3 # v4
         with:
           ref: ${{ github.event.inputs.tag }}
-      - name: Npm Install
-        run: npm install && cd apps && npm install
-      - name: Build
-        run: cd apps && npx vite build --config ${{ github.event.inputs.app }}/vite.config.js --mode ${{ github.event.inputs.env }}
+      - name: Install & Build
+        run: npm i && cd webs/apps/${{ github.event.inputs.app }} && npm run build --mode ${{ github.event.inputs.env }}
         # run: npm run build # will create a dist folder (tbd build environment??)
       - name: upload artifact
         uses: actions/upload-artifact@v4
         with:
           name: my-build
-          path: ${{ github.workspace }}/apps/${{ github.event.inputs.app }}/dist
+          path: ${{ github.workspace }}/webs/apps/${{ github.event.inputs.app }}/dist
   deploy-oss: # aliyun OSS
     needs: run-build
     if: github.event.inputs.provider == 'oss'
@@ -88,7 +87,7 @@ jobs:
         uses: actions/download-artifact@v4
         with:
           name: my-build
-          path: ${{ github.workspace }}/apps/${{ github.event.inputs.app }}/dist
+          path: ${{ github.workspace }}/webs/apps/${{ github.event.inputs.app }}/dist
       - name: Install Alibaba Cloud OSSUTIL
         run: wget http://gosspublic.alicdn.com/ossutil/1.6.10/ossutil64 && chmod +x ossutil64
       - name: Configure Alibaba Cloud OSSUTIL
@@ -104,7 +103,7 @@ jobs:
         uses: actions/download-artifact@v4
         with:
           name: my-build
-          path: ${{ github.workspace }}/apps/${{ github.event.inputs.app }}/dist
+          path: ${{ github.workspace }}/webs/apps/${{ github.event.inputs.app }}/dist
       - name: Setup AWS CLI
         uses: aws-actions/configure-aws-credentials@v1
         with:
@@ -115,25 +114,73 @@ jobs:
         run: |
           aws s3 sync dist s3://${{ github.event.inputs.bucket }} --delete
   deploy-oss2: # Alibaba Cloud OSS via AWS CLI
-      needs: run-build
-      if: github.event.inputs.provider == 'oss2'
-      runs-on: ubuntu-latest
-      steps:
-        - name: Download artifact
-          uses: actions/download-artifact@v4
-          with:
-            name: my-build
-            path: ${{ github.workspace }}/apps/${{ github.event.inputs.app }}/dist
+    needs: run-build
+    if: github.event.inputs.provider == 'oss2'
+    runs-on: ubuntu-latest
+    steps:
+      - name: Download artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: my-build
+          path: ${{ github.workspace }}/webs/apps/${{ github.event.inputs.app }}/dist
+      - name: Configure AWS CLI for OSS
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
+          aws-region: ap-southeast-1
+      - name: Sync files to OSS bucket
+        run: |
+          aws s3 sync dist s3://${{ github.event.inputs.bucket }} \
+            --delete \
+            --endpoint-url https://${{ secrets.OSS_ENDPOINT }}
+  deploy-ghp: # Alibaba Cloud OSS via AWS CLI
+    needs: run-build
+    if: github.event.inputs.provider == 'ghp'
+    runs-on: ubuntu-latest
+    steps:
+      - name: Download artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: my-build
+          path: ${{ github.workspace }}/webs/apps/${{ github.event.inputs.app }}/dist
+      - name: Run deploy script
+        # remember to change user.name and user.email
+        run: |
+          git config user.name "Your username" && git config user.email "your email"
+          git checkout --orphan gh-pages
+          npx vite build --mode ${{ github.event.inputs.environment }}
+          git --work-tree dist add --all
+          git --work-tree dist commit -m 'Deploy'
+          git push origin HEAD:gh-pages --force
+          rm -r dist
+          git checkout -f ${GITHUB_REF##*/}
+          git branch -D gh-pages
 
-        - name: Configure AWS CLI for OSS
-          uses: aws-actions/configure-aws-credentials@v1
-          with:
-            aws-access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
-            aws-secret-access-key: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
-            aws-region: ap-southeast-1
+  # # https://cli.vuejs.org/guide/deployment.html#github-pages
 
-        - name: Sync files to OSS bucket
-          run: |
-            aws s3 sync dist s3://${{ github.event.inputs.bucket }} \
-              --delete \
-              --endpoint-url https://${{ secrets.OSS_ENDPOINT }}
+# #!/usr/bin/env sh
+
+# # abort on errors
+# set -e
+
+# # build
+# npm run build
+
+# # navigate into the build output directory
+# cd dist
+
+# # if you are deploying to a custom domain
+# # echo 'www.example.com' > CNAME
+
+# git init
+# git add -A
+# git commit -m 'deploy'
+
+# # if you are deploying to https://<USERNAME>.github.io
+# # git push -f git@github.com:<USERNAME>/<USERNAME>.github.io.git master
+
+# # if you are deploying to https://<USERNAME>.github.io/<REPO>
+# # git push -f git@github.com:<USERNAME>/<REPO>.git master:gh-pages
+
+# cd -
